#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
if [ -f ".TAG" ]; then

    latest_tag=$(git describe --tags --abbrev=0)
    tag_content=$(cat .TAG)

    if [ "$latest_tag" == "$tag_content" ]
    then
    echo "Error: .TAG file is not updated. Version is already released. Please update .TAG file"
    exit 1
    fi
fi

